language: android
sudo: required
jdk: oraclejdk8
android:
  components:
    - build-tools-29.0.2
    - android-28
    
before_install:
   - chmod +x gradlew
   
script:
    - ./gradlew test --stacktrace
