language: android
sudo: required
jdk: oraclejdk8
android:
  components:
    - build-tools-29.0.2
    - android-28
    
before_install:
    - yes | sdkmanager "platforms;android-27"
    - yes | sdkmanager "platforms;android-28"
   
script:
    - ./gradlew test --stacktrace
